### ISSUE TITLE
global.css not found on EAS Build for Android

### ISSUE THREAD

**Issue by ashleyrudland** [nativewind/nativewind#1057]
**Describe the bug**
global.css not found when building with EAS Build for Android. Here's the error from EAS Build:

<img width="1275" alt="Screenshot 2024-09-10 at 22 18 32" src="https://github.com/user-attachments/assets/047ba0c3-e0c0-465d-a40e-08bd8e26fbe9">

```
> Task :app:createBundleReleaseJsAndAssets FAILED
Error: Unable to resolve module ./global.css from /home/expo/workingdir/build/apps/mobile/App.tsx: ./global.css could not be found within the project or in these directories:
  node_modules
> 1 | import './global.css';
    |         ^
  2 |
  3 | import { Ionicons } from '@expo/vector-icons';
  4 | import AsyncStorage from '@react-native-async-storage/async-storage';
Error: Unable to resolve module ./global.css from /home/expo/workingdir/build/apps/mobile/App.tsx: ./global.css could not be found within the project or in these directories:
  node_modules
> 1 | import './global.css';
    |         ^
  2 |
  3 | import { Ionicons } from '@expo/vector-icons';
  4 | import AsyncStorage from '@react-native-async-storage/async-storage';
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/node-haste/DependencyGraph.js:232:43)
    at /home/expo/workingdir/build/apps/mobile/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at visit (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 0)
    at buildSubgraph (/home/expo/workingdir/build/apps/mobile/node_modules/metro/src/DeltaBundler/buildSubgraph.js:103:3)
> Task :app:createBundleReleaseJsAndAssets_SentryUpload_com.dealsourcr.dsapp@17.4.0+105_105 FAILED
```

**Reproduction**

babel.config.js
```js
module.exports = function (api) {
	api.cache(true);

	return {
		presets: [
			['babel-preset-expo', { jsxImportSource: 'nativewind' }],
			'nativewind/babel',
		],
		plugins: ['react-native-reanimated/plugin'],
	};
};
```

metro.config.js
```js
const { withNativeWind } = require('nativewind/metro');
const { getSentryExpoConfig } = require('@sentry/react-native/metro');

// eslint-disable-next-line no-undef
const config = getSentryExpoConfig(__dirname, {
	isCSSEnabled: true,
});

module.exports = withNativeWind(config, {
	input: './global.css',
	inlineRem: 16,
});
```

tailwind.config.js
```js
module.exports = {
	darkMode: 'class',
	content: [
		'./components/**/*.{js,jsx,ts,tsx}',
		'./navigation/**/*.{js,jsx,ts,tsx}',
		'./screens/**/*.{js,jsx,ts,tsx}',
		'./App.tsx',
	],
	presets: [require('nativewind/preset')],
	...
```

deps:
- nativewind: 4.1.7
- tailwindcss: 3.4.10
- expo: 51.0.31

**Expected behavior**
Build to complete successfully, worked perfect for iOS.

**Additional context**
No issues locally, everything works. iOS build successful, purely an issue on EAS Build for this. I tried generating the global.css export via the postinstall script as mentioned on other tickets for similar issues, to no avail.

Do you have an example codebase/app that builds to Android successfully?

**Comment by marklawlor** [comment]
We need a full reproduction to be able to test your project. Snippets of files is not enough for us to test your issue

**Comment by ashleyrudland** [comment]
Do you have an android build working?

**Comment by ashleyrudland** [comment]
I found the issue @marklawlor - it's the latest version of NativeWind (`4.1.7`), with `4.0.36` it works fine

**Comment by ashleyrudland** [comment]
You should add eas build for ios and android to this repo so all changes are tested

**Comment by marklawlor** [comment]
My EAS builds are passing with `4.1.7` - this is why I need a test reproduction. Builds are highly sensitive to small things like environment variables or changes to the metro config. If I have a test reproduction this is much easier for both of us, as I can simply run the code, see the error and fix it.
