### ISSUE TITLE
[v4.1.11]+ Does not work with react-native-web

### ISSUE THREAD

**Issue by divineniiquaye** [nativewind/nativewind#1136]
After the version v4.1.11+, nativewind does not work with react-native-web any longer. I tried all latest versions up to the latest v4.1.16 and got a `TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function` error.

Here's the stack trace and I've reproduced the issue in [This repo under nativewind branch](https://github.com/divineniiquaye/nativewind-issue-1115/tree/nativewind):

```
 ✓ Starting...
 ✓ Ready in 1816ms
 ○ Compiling / ...
 ✓ Compiled / in 19.1s (6267 modules)
TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/modules/useLocale/index.js:23:87)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/modules/useLocale/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:3140:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/exports/createElement/index.js:9:76)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/exports/createElement/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:2750:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/index.js:65:80)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:2830:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/third-party-libs/react-native-safe-area-context.js:7:24)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/third-party-libs/react-native-safe-area-context.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:344:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/wrap-jsx.js:7:42)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/wrap-jsx.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:378:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/jsx-dev-runtime.js:13:36)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/jsx-dev-runtime.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:274:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:6:84)
    at (rsc)/./app/layout.tsx (/workspace/nativewind-issue-1115/.next/server/app/page.js:283:1)
    at Function.__webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at async e7 (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396619)
    at async tS (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400214)
    at async tw (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400775)
    at async tO (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2320)
    at async /workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2989 {
  digest: '1232379046'
}
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:6:84)
    at (rsc)/./app/layout.tsx (/workspace/nativewind-issue-1115/.next/server/app/page.js:283:1)
    at Function.__webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
digest: "2940864934"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:6:84)
    at (rsc)/./app/layout.tsx (/workspace/nativewind-issue-1115/.next/server/app/page.js:283:1)
    at Function.__webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
digest: "2940864934"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (./app/layout.tsx:6:84)
    at (rsc)/./app/layout.tsx (/workspace/nativewind-issue-1115/.next/server/app/page.js:283:1)
    at Function.__webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
digest: "1232379046"
 ⨯ TypeError: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/modules/useLocale/index.js:23:87)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/modules/useLocale/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:3140:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/exports/createElement/index.js:9:76)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/exports/createElement/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:2750:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/index.js:65:80)
    at (rsc)/./node_modules/.pnpm/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/react-native-web/dist/index.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-web@0.19.12_react-dom@18.3.1_react@18.3.1__react@18.3.1.js:2830:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/third-party-libs/react-native-safe-area-context.js:7:24)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/third-party-libs/react-native-safe-area-context.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:344:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/wrap-jsx.js:7:42)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/wrap-jsx.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:378:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/jsx-dev-runtime.js:13:36)
    at (rsc)/./node_modules/.pnpm/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe/node_modules/react-native-css-interop/dist/runtime/jsx-dev-runtime.js (/workspace/nativewind-issue-1115/.next/server/vendor-chunks/react-native-css-interop@0.1.15_react-native-reanimated@3.15.4_@babel+core@7.25.7_react-nativ_cynlgcoibu7yq7kfnk4ckdjsxe.js:274:1)
    at __webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./app/layout.tsx:6:84)
    at (rsc)/./app/layout.tsx (/workspace/nativewind-issue-1115/.next/server/app/page.js:283:1)
    at Function.__webpack_require__ (/workspace/nativewind-issue-1115/.next/server/webpack-runtime.js:33:43)
    at async e7 (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:396619)
    at async tS (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400214)
    at async tw (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:400775)
    at async tO (/workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2320)
    at async /workspace/nativewind-issue-1115/node_modules/.pnpm/next@14.2.14_@babel+core@7.25.7_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:36:2989 {
  digest: '1232379046',
  page: '/'
}
 ○ Compiling /_error ...
 ✓ Compiled /_error in 11s (6492 modules)
 GET / 500 in 30691ms
```

**Comment by danstepanov** [comment]
Please create a more isolated repro, this seems like a fork of a codebase?

**Comment by cmaycumber** [comment]
Also running into this issue when bumping above v4.1.10.

**Comment by divineniiquaye** [comment]
@danstepanov  It's working now in version v4.1.21
