### ISSUE TITLE
lightningcss transform failure after upgrading from 4.0.36 to 4.1.23 - SyntaxError: Unknown at rule: @rn-move

### ISSUE THREAD

**Issue by vktrl** [nativewind/nativewind#1183]
Bundling for iOS fails after upgrading to 4.1. Here's what I see in the output:
```
 nativewind getTransformOptions.dev true +21s
  nativewind getTransformOptions.platform ios +0ms
  nativewind getTransformOptions.virtualModulesPossible true +0ms
  nativewind virtualModules /Users/vktrl/Projects/v3/node_modules/react-native-css-interop/.cache/ios.js +0ms
  nativewind virtualModules.isDev true +0ms
  nativewind virtualModules.size 0 +0ms
  nativewind virtualModules.fastRefresh enabled +0ms
  nativewind getCSSForPlatform: ios +21s
  nativewind Start development Tailwind CLI +0ms
  nativewind getTransformOptions.writeToFileSystem false +1ms
iOS ./index.ts ░░░░░░░░░░░░░░░░  4.0% (1/5)  nativewind Finished initial development Tailwind CLI +812ms
  nativewind virtualStyles.initial ios +811ms
  react-native-css-interop Features {"transformPercentagePolyfill":true,"disableGapPercentageValues":true,"disableDisplayBlock":false,"disableAlignContentEvenly":false,"disablePositionStatic":false} +0ms
  react-native-css-interop Grouping /^group(\/.*)?/ +0ms
  react-native-css-interop Start lightningcss +0ms
/Users/vktrl/Projects/v3/node_modules/react-native-css-interop/dist/css-to-rn/index.js:49
    (0, lightningcss_1.transform)({
                                 ^

SyntaxError: Unknown at rule: @rn-move
    at cssToReactNativeRuntime (/Users/vktrl/Projects/v3/node_modules/react-native-css-interop/src/css-to-rn/index.ts:125:15)
    at /Users/vktrl/Projects/v3/node_modules/react-native-css-interop/src/metro/index.ts:361:48
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  fileName: 'style.css',
  source: '@cssInterop set darkMode class dark;\n' +
    '\n' +
    '@cssInterop set nativewind;\n' +
    '\n' +
    [ truncated css ]
    '  height: 3r'... 93470 more characters,
  loc: { line: 2903, column: 11 },
  data: { type: 'AtRuleInvalid', value: 'rn-move' }
}
```

I've cleared and reinstalled node_modules, build cache, made sure expo is happy with the dependencies, but no dice.

I wasn't able to reproduce this in a new project with same dependencies. The error goes away if I exclude components from tailwind config content paths, so it probably has something to do with css generated by nativewind somewhere in a component or its external dependency.

Went through the versions and found that the last working one is `4.1.10`.

```
nativewind: 4.1.23
react-native: 0.74.5
tailwindcss: 3.4.14
expo: 51.0.38
```

**Comment by vktrl** [comment]
Managed to narrow down the JSX causing the issue, but the behavior is weird:
```tsx
<View style={{ backgroundColor: '#1877F2' }} className="mr-2 h-5 w-5">
  <Icon className="fill-white" />  // this would cause a crash
  {/* <Icon className="fill-white" /> */} // this would also crash
</View>
```
Deleting the Icon component line would fix the problem.

Final fix was deleting `node_modules`, deleting the lockfile, and upgrading all packages several times in a different order. The resolved versions for nativewind, react-native-css-interop, expo, react-native, tailwindss and lightningcss haven't changed according to the lockfile, so no idea what was going on there.

Using bun 1.1.33 on macos.
