### ISSUE TITLE
Tailwind PostCSS configuration instructions seems wrong

### ISSUE THREAD

**Issue by nchase** [nativewind/nativewind#381]
First of all, this project is great. Thank you for it! It has been really useful so far.

**Describe the bug**
The Web instructions [here](https://www.nativewind.dev/guides/postcss#web) say to configure tailwind.config.js as follows:

```diff
// tailwind.config.js
+ const nativewind = require("nativewind/tailwind/css")
+
module.exports = {
  content: [
    './App.{js,ts,jsx,tsx}',
  ],
+ plugins: [nativewind()],
};
```

When I do this, the bundler throws an error. 

 
**To Reproduce**
I followed the instructions at https://www.nativewind.dev/guides/postcss#web (see above)

**Screenshots**
Here's the output I get in my project:

```
✖ ｢wdm｣: ERROR in ./client/index.tsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: [BABEL] /Users/userName/etc/code/projects/projectName/client/index.tsx: nativewind is not a function (While processing: "/Users/userName/etc/code/projects/projectName/node_modules/nativewind/babel.js")
    at Object.<anonymous> (/Users/userName/etc/code/projects/projectName/tailwind.config.js:8:13)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at apply (/Users/userName/etc/code/projects/projectName/node_modules/nativewind/dist/babel/index.js:38:28)
    at async (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/gensync-utils/async.ts:36:33)
    at async (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:186:15)
    at factory (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at /Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/full.ts:265:23
    at Generator.next (<anonymous>)
    at Function.<anonymous> (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/gensync-utils/async.ts:10:3)
    at Generator.next (<anonymous>)
    at step (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:269:25)
    at evaluateAsync (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:291:5)
    at Function.errback (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:113:7)
    at errback (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/gensync-utils/async.ts:88:18)
    at async (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:188:17)
    at onFirstPause (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at pluginDescriptorLoader (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/caching.ts:131:34)
    at cachedFunction.next (<anonymous>)
    at loadPluginDescriptor (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/full.ts:404:12)
    at loadPluginDescriptor.next (<anonymous>)
    at fn (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/full.ts:185:33)
    at loadPluginDescriptors.next (<anonymous>)
    at /Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/full.ts:218:21
    at Generator.next (<anonymous>)
    at loadFullConfig (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/config/full.ts:199:5)
    at loadFullConfig.next (<anonymous>)
    at transform (/Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/transform.ts:26:58)
    at transform.next (<anonymous>)
    at step (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:269:25)
    at /Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:223:11)
    at cb (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:189:28)
    at /Users/userName/etc/code/projects/projectName/node_modules/@babel/core/src/gensync-utils/async.ts:90:7
    at /Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:113:33
    at step (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:287:14)
    at /Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/userName/etc/code/projects/projectName/node_modules/gensync/index.js:223:11)
```

**Comment by michaelkremenetsky** [comment]
Try `plugins: [nativewind]` instead of `plugins: [nativewind()]`.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
