### ISSUE TITLE
Cannot start expo after installing NativeWInd v4

### ISSUE THREAD

**Issue by script8888** [nativewind/nativewind#871]
**Describe the bug**
When I run `yarn run ios`, I get this error in terminal:
```txt
tailwindcss(ios) rebuilding... tailwindcss(ios) is taking a long time to build, 
please read https://tailwindcss.com/docs/content-configuration#pattern-recommendations to 
speed up your build time
```

**To Reproduce**
- Follow all the steps on setting up native wind from the docs [https://www.nativewind.dev/v4/getting-started/expo-router](https://www.nativewind.dev/v4/getting-started/expo-router)

**Expected behavior**
App preview is supposed to load up.

**Screenshots**
This is what my expo app shows up.
<img width="326" alt="image" src="https://github.com/marklawlor/nativewind/assets/52074770/44556d2c-74b5-45e3-8b8a-a0baee4d001b">

Files:
my `global.css` is located at the root dir of the project

```js
// tailwind.config.js

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

```js
// babel.config.js

module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
    plugins: [
      // Required for expo-router
      "expo-router/babel",
      "react-native-reanimated/plugin",
    ]
  };
};
```

```js
// metro.config.js

// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname, { isCSSEnabled: true });

module.exports = withNativeWind(config, { input: "./global.css" });
```

**Comment by Aycom366** [comment]
expo already added the reanimated plugin to their babel-preset-expo, so you don't have to set that again provided you're using SDK 50, and of cause, This might not fix it.

**Comment by agrittiwari** [comment]
```

TypeError: withNativeWind is not a function
TypeError: withNativeWind is not a function
    at Object.<anonymous> (/Users/agrittiwari/OpenSource/devStory/metro.config.js:10:18)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1234:19)
    at require (node:internal/modules/helpers:176:18)
    at module.exports (/Users/agrittiwari/OpenSource/devStory/node_modules/import-fresh/index.js:28:9)
    at loadJs (/Users/agrittiwari/OpenSource/devStory/node_modules/cosmiconfig/dist/loaders.js:9:18)
    at Explorer.loadFileContent (/Users/agrittiwari/OpenSource/devStory/node_modules/cosmiconfig/dist/createExplorer.js:230:12)
```

how to add nativewind/metro, if you've added this in package.json @script8888

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by hirwaaldo1** [comment]
With SDK 53, I had an issue where styles were not being applied. I fixed it by updating the metro.config.js as shown below:

```js 
const { withNativeWind } = require("nativewind/metro");
const { getSentryExpoConfig } = require("@sentry/react-native/metro");

/** @type {import('expo/metro-config').MetroConfig} */
// const config = getDefaultConfig(__dirname);

const config = getSentryExpoConfig(__dirname);
// config.resolver.assetExts.push('css');
config.resolver.unstable_enablePackageExports = false;
config.transformer.minifierConfig = {
  keep_quotes: true,
};

config.resolver.sourceExts.push('css');


config.transformer.getTransformOptions = async () => ({
  transform: {
    experimentalImportSupport: false,
    inlineRequires: false,
  },
});

module.exports = withNativeWind(config, {
  input: "./global.css",
});

```
